# configs/train/optuna.yaml
enabled: true
trials: 10
search_space:
  lr: [5e-5, 1e-4, 3e-4]
  weight_decay: [0.0, 0.01, 0.05]
  batch_size: [32, 64, 96]
  dropout: [0.0, 0.1, 0.2, 0.3]
opt_metric: "f1"
direction: "maximize"
